# mysql
spring:
  datasource:
    url: jdbc:mysql://192.168.107.3:3306/springcloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

swagger:
  enabled: true

config:
  name: 【main】分支_【springcloud-user-server】项目application_【dev】配置文件profile
