# mysql
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/education_user?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: roncoo
    password: T6TB886i3+HLzfu1YDyCi0Ev82LWLBX9ri+e2eHCK+iF/t+yl0Z8nc4lRKdPew2Y4m4VaaaXqLWYWnlCLdPHSw==

swagger:
  enabled: true
